version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blog
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d blog -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build:
      context: ./
      dockerfile: Docker/Dockerfile
    command: sh Docker/boot.sh
    volumes:
      -  ./:/app/

    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
        db:
          condition: service_healthy

volumes:
  postgres_data:
